name = "conceptual_mathematics"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["companion", "textbook"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
# autoImplicit = false
# relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.longLine = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.22.0"

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.22.0"

[[lean_lib]]
name = "ConceptualMathematics"

[[lean_exe]]
name = "companion"
root = "ConceptualMathematicsMain"

[[lean_lib]]
name = "DemoTextbook"

[[lean_exe]]
name = "textbook"
root = "DemoTextbookMain"
