name = "conceptual_mathematics"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["companion", "textbook"]

[leanOptions]
weak.linter.hashCommand = false
weak.linter.mathlibStandardSet = true
weak.linter.style.longLine = false
weak.linter.style.setOption = false
maxSynthPendingDepth = 3
pp.rawOnError = true
pp.unicode.fun = true
weak.verso.code.warnLineLength = 72

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.24.0"

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.24.0"

[[lean_lib]]
name = "ConceptualMathematics"

[[lean_exe]]
name = "companion"
root = "ConceptualMathematicsMain"

[[lean_lib]]
name = "DemoTextbook"

[[lean_exe]]
name = "textbook"
root = "DemoTextbookMain"
